// This file is generated by database/migrations/setup.ts. Do not modify it manually.
// Last updated 2025-10-04 21:29:37

export interface chat_messages {
    id: string;
    created_at: string;
    chat_id: string;
    message: string;
    role: string;
}
