// This file is generated by database/migrations/setup.ts. Do not modify it manually.
// Last updated 2025-10-05 00:22:52

export interface chat_messages {
    id: string;
    created_at: string;
    message: string;
    role: string;
}
