// This file is generated by database/migrations/setup.ts. Do not modify it manually.
// Last updated 2025-10-04 21:29:37

import { chat_messages } from "./chat_messages.ts";

export type DatabaseSchema = {
    chat_messages: chat_messages
};
