services:
  # backend:
  #   container_name: gaus-backend
  #   build: ./backend
  #   depends_on:
  #     - db
  #   ports:
  #     - "8081:8081"
  #   env_file:
  #     - .env
  #   environment:
  #     - NODE_ENV=local-docker
  #     - POSTGRES_HOST=db
  db:
    image: postgres:15
    container_name: gaus-db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: